### ISSUE TITLE
Multi-Part Composite Key causes "Find" Exception using tryFindEntity / updateEntity

### ISSUE THREAD

**Issue by kirse** [efcore/EFCore.FSharp#131]
General setup:
```fsharp
// Whatever context config, but create an entity with composite key:
modelBuilder.Entity<CompositeKeyEntity>().HasKey([| "Key1"; "Key2"; "KeyN" |]) |> ignore
```
Then try:
```fsharp
tryFindEntity<CompositeKeyEntity> db (fun (x : CompositeKeyEntity) -> (x.Key1, x.Key2, x.KeyN) :> obj)
```

Or this:
```fsharp
tryFindEntity<CompositeKeyEntity> db (fun (x : CompositeKeyEntity) -> 
    let key : obj[] = [| x.Key1; x.Key2; x.KeyN |]
    key)
```

Which causes this:

```
System.ArgumentException: Entity type 'CompositeKeyEntity' is defined with a 3-part composite key, but 1 values were passed to the 'Find' method.
at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
```

Not hugely impactful since `.Find()` can be used directly, but treating `key` as `obj` instead of `obj[]` means composite keys can't be used with the helper functions (and they are helpful in many cases).

**Comment by simon-reynolds** [comment]
This has been fixed in v6.0.6

The only caveat is that a composite key has to be an `obj[]` or `obj list`, so you'd need to use the second option above

```fsharp
tryFindEntity<CompositeKeyEntity> db (fun (x : CompositeKeyEntity) -> 
    let key : obj[] = [| x.Key1; x.Key2; x.KeyN |]
    key)
```

**Comment by kirse** [comment]
Awesome, thanks!

**Comment by simon-reynolds** [comment]
Thank you, it's always great to hear when someone is getting some use out of it

**Comment by kirse** [comment]
On rev-ing to 6.0.6 it appears the new helper methods now return everything of type `obj` instead of `'a`, is this intended?

Ex:
```fsharp
let myEnt = tryFindEntity<CompositeKeyEntity> db id
// type of myEnt is now obj instead of CompositeKeyEntity
```
