### ISSUE TITLE
NullReferenceException on second migration

### ISSUE THREAD

**Issue by EspenBrun** [efcore/EFCore.FSharp#151]
**Describe the bug**
`Object reference not set to an instance of an object` when running second migration.

I think this is a problem for me specifically, but I have tried quite a lot of things and I am completely stuck, and it is blocking my usage of EF for F#.

I am using entity framework in an F# project (SAFE-stack) and I can create the initial migration, but when I try to do another migration it fails with a NullReferenceException.

I'm on a SAFE-template 3.1.1, but if I add entity framework to a new safe-template 3.1.1 it works fine. I suspect it is something wrong with my paket.lock, but I am not sure, and I have not had any success in fixing ut.

**To Reproduce**
I am not able to reproduce in a simpler project. I wonder if it could 

**Expected behavior**
A new migration does not give me a an error.

**Screenshots**
```
❯ dotnet ef migrations add Test --verbose         
Using project '/Users/espen/code/horus/src/Server/Server.fsproj'.
Using startup project '/Users/espen/code/horus/src/Server/Server.fsproj'.
Writing '/Users/espen/code/horus/src/Server/obj/Server.fsproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/sb/g7_08qr135x_00vnhvz0hqqc0000gn/T/tmp509y63.tmp /verbosity:quiet /nologo /Users/espen/code/horus/src/Server/Server.fsproj
Writing '/Users/espen/code/horus/src/Server/obj/Server.fsproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/sb/g7_08qr135x_00vnhvz0hqqc0000gn/T/tmp4U1rqW.tmp /verbosity:quiet /nologo /Users/espen/code/horus/src/Server/Server.fsproj
Build started...
dotnet build /Users/espen/code/horus/src/Server/Server.fsproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:13.26
Build succeeded.
dotnet exec --depsfile /Users/espen/code/horus/src/Server/bin/Debug/net5.0/Server.deps.json --additionalprobingpath /Users/espen/.nuget/packages --additionalprobingpath /usr/local/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /Users/espen/code/horus/src/Server/bin/Debug/net5.0/Server.runtimeconfig.json /Users/espen/.nuget/packages/dotnet-ef/5.0.17/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations add Test --assembly /Users/espen/code/horus/src/Server/bin/Debug/net5.0/Server.dll --startup-assembly /Users/espen/code/horus/src/Server/bin/Debug/net5.0/Server.dll --project-dir /Users/espen/code/horus/src/Server/ --language F# --working-dir /Users/espen/code/horus/src/Server --verbose --root-namespace Server
Using assembly 'Server'.
Using startup assembly 'Server'.
Using application base '/Users/espen/code/horus/src/Server/bin/Debug/net5.0'.
Using working directory '/Users/espen/code/horus/src/Server'.
Using root namespace 'Server'.
Using project directory '/Users/espen/code/horus/src/Server/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'Server'...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'DataContext'.
Using context 'DataContext'.
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
Using design-time services from provider 'Pomelo.EntityFrameworkCore.MySql'.
Finding design-time services referenced by assembly 'Server'...
Finding design-time services referenced by assembly 'Server'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'Server'...
Using design-time services from class 'DesignTimeServices'.
'DataContext' disposed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Initialize(ColumnOperation columnOperation, IColumn column, RelationalTypeMapping typeMapping, Boolean isNullable, IEnumerable`1 migrationsAnnotations, Boolean inline)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IColumn source, IColumn target, DiffContext diffContext)+MoveNext()
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrationsModelDiffer.SkipRedundantCharSetSpecifyingAlterColumnOperations(IEnumerable`1 migrationOperations)+MoveNext()
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrationsModelDiffer.PostFilterOperations(IEnumerable`1 migrationOperations)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(ITable source, ITable target, DiffContext diffContext)+MoveNext()
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrationsModelDiffer.PostFilterOperations(IEnumerable`1 migrationOperations)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrationsModelDiffer.PostFilterOperations(IEnumerable`1 migrationOperations)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

My paket.lock file locks looks like this:

```
STORAGE: NONE
RESTRICTION: == net5.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    Auth0.AspNetCore.Authentication (1.0.4)
      Microsoft.AspNetCore.Authentication.OpenIdConnect (>= 5.0.17)
      System.Text.Encodings.Web (>= 4.5.1)
    Azure.Core (1.20)
      Microsoft.Bcl.AsyncInterfaces (>= 1.0)
      System.Diagnostics.DiagnosticSource (>= 4.6)
      System.Memory.Data (>= 1.0.2)
      System.Numerics.Vectors (>= 4.5)
      System.Text.Encodings.Web (>= 4.7.2)
      System.Text.Json (>= 4.6)
      System.Threading.Tasks.Extensions (>= 4.5.4)
    Azure.Identity (1.4.1)
      Azure.Core (>= 1.17)
      Microsoft.Identity.Client (>= 4.30.1)
      Microsoft.Identity.Client.Extensions.Msal (>= 2.18.4)
      System.Memory (>= 4.5.4)
      System.Security.Cryptography.ProtectedData (>= 4.5)
      System.Text.Json (>= 4.6)
      System.Threading.Tasks.Extensions (>= 4.5.2)
    Azure.Security.KeyVault.Certificates (4.2)
      Azure.Core (>= 1.15)
      System.Memory (>= 4.5.4)
      System.Text.Json (>= 4.6)
      System.Threading.Tasks.Extensions (>= 4.5.2)
    Azure.Security.KeyVault.Secrets (4.2)
      Azure.Core (>= 1.15)
      System.Memory (>= 4.5.4)
      System.Text.Json (>= 4.6)
      System.Threading.Tasks.Extensions (>= 4.5.2)
    Elmish.SweetAlert (3.4)
      Fable.Core (>= 3.1.3)
      Fable.Elmish (>= 3.0)
      FSharp.Core (>= 4.7.2)
    EntityFrameworkCore.FSharp (5.0.3)
      FSharp.Core (>= 5.0)
      Microsoft.EntityFrameworkCore.Design (>= 5.0.3)
    Expecto (9.0.4)
      FSharp.Core (>= 4.6)
      Mono.Cecil (>= 0.11.3)
    Fable.AST (3.1.1)
    Fable.Browser.Blob (1.1.4)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Browser.Dom (2.6)
      Fable.Browser.Blob (>= 1.1.4)
      Fable.Browser.Event (>= 1.4.5)
      Fable.Browser.WebStorage (>= 1.0.4)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Browser.Event (1.4.5)
      Fable.Browser.Gamepad (>= 1.0.3)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Browser.Gamepad (1.0.3)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Browser.WebStorage (1.0.4)
      Fable.Browser.Event (>= 1.4.4)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Browser.XMLHttpRequest (1.1.6)
      Fable.Browser.Blob (>= 1.1.4)
      Fable.Browser.Event (>= 1.4.4)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Fable.Core (3.7.1)
    Fable.Elmish (3.1)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.Browser (3.0.4)
      Fable.Browser.Dom (>= 1.0)
      Fable.Core (>= 3.0)
      Fable.Elmish (>= 3.0)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.Debugger (3.3)
      Fable.Core (>= 3.2.8)
      Fable.Elmish (>= 3.0)
      FSharp.Core (>= 4.7.2)
      Thoth.Json (>= 6.0)
    Fable.Elmish.HMR (4.1)
      Fable.Core (>= 3.0)
      Fable.Elmish.Browser (>= 3.0.4)
      Fable.Elmish.React (>= 3.0.1)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.React (3.0.1)
      Fable.Core (>= 3.0)
      Fable.Elmish (>= 3.0)
      Fable.React (>= 5.1)
      FSharp.Core (>= 4.6.2)
    Fable.FontAwesome (2.0)
      Fable.Core (>= 3.0)
      Fable.React (>= 5.1)
    Fable.FontAwesome.Free (2.1)
      Fable.Core (>= 3.0)
      Fable.FontAwesome (>= 2.0)
      Fable.React (>= 5.1)
    Fable.GroupingPanel (0.3.1)
      Fable.React (>= 6.2)
      Fable.SimpleJson (>= 3.11)
      FSharp.Core (>= 4.7.2)
    Fable.Mocha (2.10)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.7)
    Fable.Parsimmon (4.1)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.6.2)
    Fable.React (8.0.1)
      Fable.Browser.Dom (>= 2.4.4)
      Fable.Core (>= 3.2.7)
      FSharp.Core (>= 4.7.2)
    Fable.Remoting.Client (7.16)
      Fable.Browser.XMLHttpRequest (>= 1.0)
      Fable.Core (>= 3.1.5)
      Fable.Remoting.MsgPack (>= 1.13)
      Fable.SimpleJson (>= 3.21)
      FSharp.Core (>= 4.7)
    Fable.Remoting.Giraffe (5.5)
      Fable.Remoting.Server (>= 5.25)
      FSharp.Core (>= 5.0)
      Giraffe (>= 5.0)
    Fable.Remoting.Json (2.19)
      FSharp.Core (>= 4.7.2)
      Newtonsoft.Json (>= 12.0.2)
    Fable.Remoting.MsgPack (1.13)
      FSharp.Core (>= 4.7.2)
    Fable.Remoting.Server (5.25)
      Fable.Remoting.Json (>= 2.19)
      Fable.Remoting.MsgPack (>= 1.13)
      FSharp.Core (>= 4.7.2)
    Fable.SimpleJson (3.21)
      Fable.Core (>= 3.1.5)
      Fable.Parsimmon (>= 4.0)
      FSharp.Core (>= 4.7)
    Fake.Core.CommandLineParsing (5.20.4)
      FParsec (>= 1.1.1)
      FSharp.Core (>= 4.7.2)
    Fake.Core.Context (5.20.4)
      FSharp.Core (>= 4.7.2)
    Fake.Core.Environment (5.20.4)
      FSharp.Core (>= 4.7.2)
    Fake.Core.FakeVar (5.20.4)
      Fake.Core.Context (>= 5.20.4)
      FSharp.Core (>= 4.7.2)
    Fake.Core.Process (5.20.4)
      Fake.Core.Environment (>= 5.20.4)
      Fake.Core.FakeVar (>= 5.20.4)
      Fake.Core.String (>= 5.20.4)
      Fake.Core.Trace (>= 5.20.4)
      Fake.IO.FileSystem (>= 5.20.4)
      FSharp.Core (>= 4.7.2)
      System.Collections.Immutable (>= 1.7.1)
    Fake.Core.String (5.20.4)
      FSharp.Core (>= 4.7.2)
    Fake.Core.Target (5.20.4)
      Fake.Core.CommandLineParsing (>= 5.20.4)
      Fake.Core.Context (>= 5.20.4)
      Fake.Core.Environment (>= 5.20.4)
      Fake.Core.FakeVar (>= 5.20.4)
      Fake.Core.Process (>= 5.20.4)
      Fake.Core.String (>= 5.20.4)
      Fake.Core.Trace (>= 5.20.4)
      FSharp.Control.Reactive (>= 4.4.2)
      FSharp.Core (>= 4.7.2)
    Fake.Core.Trace (5.20.4)
      Fake.Core.Environment (>= 5.20.4)
      Fake.Core.FakeVar (>= 5.20.4)
      FSharp.Core (>= 4.7.2)
    Fake.IO.FileSystem (5.20.4)
      Fake.Core.String (>= 5.20.4)
      FSharp.Core (>= 4.7.2)
    Farmer (1.6.16)
      FSharp.Core (>= 5.0)
    Feliz (1.67)
      Fable.Core (>= 3.1.5)
      Fable.React (>= 7.4)
      Feliz.CompilerPlugins (>= 1.10)
      FSharp.Core (>= 4.7.2)
    Feliz.CompilerPlugins (1.10)
      Fable.AST (>= 3.0)
      FSharp.Core (>= 4.7.2)
    Feliz.DaisyUI (2.0)
      Feliz (>= 1.32)
      FSharp.Core (>= 4.7.2)
    Feliz.Recharts (3.14)
      Feliz (>= 1.65)
      FSharp.Core (>= 4.7.2)
    Feliz.Router (3.8)
      Fable.Core (>= 3.1.6)
      Fable.Elmish (>= 3.1)
      Feliz (>= 1.28)
      Feliz.UseListener (>= 0.6.3)
      FSharp.Core (>= 4.7.2)
    Feliz.UseListener (0.6.3)
      Fable.Core (>= 3.1.6 < 4.0)
      Feliz (>= 1.17 < 2.0)
      FSharp.Core (>= 4.7.2)
    FParsec (1.1.1)
      FSharp.Core (>= 4.3.4)
    FSharp.Control.Reactive (5.0.2)
      FSharp.Core (>= 4.7.2)
      System.Reactive (>= 5.0)
    FSharp.Control.Websockets (0.2.2)
      FSharp.Core (>= 4.3.4)
      Microsoft.IO.RecyclableMemoryStream (>= 1.2.2)
    FSharp.Core (6.0.5)
    Giraffe (5.0)
      FSharp.Core (>= 5.0)
      Giraffe.ViewEngine (>= 1.3)
      Microsoft.IO.RecyclableMemoryStream (>= 1.3.6)
      Newtonsoft.Json (>= 12.0.3)
      Ply (>= 0.3.1)
      System.Text.Json (>= 5.0.2)
      Utf8Json (>= 1.3.7)
    Giraffe.ViewEngine (1.4)
      FSharp.Core (>= 5.0)
    Google.Protobuf (3.21.5)
    K4os.Compression.LZ4 (1.2.16)
    K4os.Compression.LZ4.Streams (1.2.16)
      K4os.Compression.LZ4 (>= 1.2.16)
      K4os.Hash.xxHash (>= 1.0.6)
    K4os.Hash.xxHash (1.0.7)
    Microsoft.AspNetCore.Authentication.JwtBearer (5.0.10)
      Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.7.1)
    Microsoft.AspNetCore.Authentication.OpenIdConnect (5.0.17)
      Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.7.1)
    Microsoft.AspNetCore.Cryptography.Internal (5.0.10)
    Microsoft.AspNetCore.DataProtection (5.0.10)
      Microsoft.AspNetCore.Cryptography.Internal (>= 5.0.10)
      Microsoft.AspNetCore.DataProtection.Abstractions (>= 5.0.10)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
      Microsoft.Extensions.Hosting.Abstractions (>= 5.0)
      Microsoft.Extensions.Logging.Abstractions (>= 5.0)
      Microsoft.Extensions.Options (>= 5.0)
      Microsoft.Win32.Registry (>= 5.0)
      System.Security.Cryptography.Xml (>= 5.0)
    Microsoft.AspNetCore.DataProtection.Abstractions (5.0.10)
    Microsoft.Bcl.AsyncInterfaces (5.0)
    Microsoft.CodeCoverage (17.3)
    Microsoft.CSharp (4.7)
    Microsoft.EntityFrameworkCore (5.0.17)
      Microsoft.EntityFrameworkCore.Abstractions (>= 5.0.17)
      Microsoft.EntityFrameworkCore.Analyzers (>= 5.0.17)
      Microsoft.Extensions.Caching.Memory (>= 5.0)
      Microsoft.Extensions.DependencyInjection (>= 5.0.2)
      Microsoft.Extensions.Logging (>= 5.0)
      System.Collections.Immutable (>= 5.0)
      System.ComponentModel.Annotations (>= 5.0)
      System.Diagnostics.DiagnosticSource (>= 5.0.1)
    Microsoft.EntityFrameworkCore.Abstractions (5.0.17)
    Microsoft.EntityFrameworkCore.Analyzers (6.0.10)
    Microsoft.EntityFrameworkCore.Design (5.0.3)
    Microsoft.EntityFrameworkCore.Relational (5.0.17)
      Microsoft.EntityFrameworkCore (>= 5.0.17)
      Microsoft.Extensions.Configuration.Abstractions (>= 5.0)
    Microsoft.Extensions.Caching.Abstractions (5.0)
      Microsoft.Extensions.Primitives (>= 5.0)
    Microsoft.Extensions.Caching.Memory (5.0)
      Microsoft.Extensions.Caching.Abstractions (>= 5.0)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
      Microsoft.Extensions.Logging.Abstractions (>= 5.0)
      Microsoft.Extensions.Options (>= 5.0)
      Microsoft.Extensions.Primitives (>= 5.0)
    Microsoft.Extensions.Configuration.Abstractions (5.0)
      Microsoft.Extensions.Primitives (>= 5.0)
    Microsoft.Extensions.DependencyInjection (5.0.2)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
    Microsoft.Extensions.DependencyInjection.Abstractions (5.0)
    Microsoft.Extensions.FileProviders.Abstractions (5.0)
      Microsoft.Extensions.Primitives (>= 5.0)
    Microsoft.Extensions.Hosting.Abstractions (5.0)
      Microsoft.Extensions.Configuration.Abstractions (>= 5.0)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
      Microsoft.Extensions.FileProviders.Abstractions (>= 5.0)
    Microsoft.Extensions.Logging (5.0)
      Microsoft.Extensions.DependencyInjection (>= 5.0)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
      Microsoft.Extensions.Logging.Abstractions (>= 5.0)
      Microsoft.Extensions.Options (>= 5.0)
    Microsoft.Extensions.Logging.Abstractions (5.0)
    Microsoft.Extensions.Options (5.0)
      Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0)
      Microsoft.Extensions.Primitives (>= 5.0)
    Microsoft.Extensions.Primitives (5.0.1)
    Microsoft.Identity.Client (4.36.2)
    Microsoft.Identity.Client.Extensions.Msal (2.19.1)
      Microsoft.Identity.Client (>= 4.36.1)
      System.Security.Cryptography.ProtectedData (>= 4.5)
    Microsoft.Identity.Web (1.17)
      Microsoft.AspNetCore.Authentication.JwtBearer (>= 5.0)
      Microsoft.AspNetCore.Authentication.OpenIdConnect (>= 5.0)
      Microsoft.Identity.Client (>= 4.36)
      Microsoft.Identity.Web.Certificate (>= 1.17)
      Microsoft.Identity.Web.TokenCache (>= 1.17)
      Microsoft.IdentityModel.Logging (>= 6.12.2)
      Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.12.2)
      System.IdentityModel.Tokens.Jwt (>= 6.12.2)
      System.Text.Encodings.Web (>= 5.0.1)
    Microsoft.Identity.Web.Certificate (1.17)
      Azure.Identity (>= 1.3)
      Azure.Security.KeyVault.Certificates (>= 4.1)
      Azure.Security.KeyVault.Secrets (>= 4.1)
      Microsoft.Identity.Client (>= 4.35.1)
      System.Text.Encodings.Web (>= 4.7.2)
    Microsoft.Identity.Web.TokenCache (1.17)
      Microsoft.AspNetCore.DataProtection (>= 5.0.8)
      Microsoft.Extensions.Caching.Memory (>= 5.0)
      Microsoft.Extensions.Logging (>= 5.0)
      Microsoft.Identity.Client (>= 4.35.1)
      System.Text.Encodings.Web (>= 5.0.1)
    Microsoft.Identity.Web.Ui (1.17)
      Microsoft.Identity.Web (>= 1.17)
    Microsoft.IdentityModel.JsonWebTokens (6.12.2)
      Microsoft.IdentityModel.Tokens (>= 6.12.2)
    Microsoft.IdentityModel.Logging (6.12.2)
    Microsoft.IdentityModel.Protocols (6.12.2)
      Microsoft.IdentityModel.Logging (>= 6.12.2)
      Microsoft.IdentityModel.Tokens (>= 6.12.2)
    Microsoft.IdentityModel.Protocols.OpenIdConnect (6.12.2)
      Microsoft.IdentityModel.Protocols (>= 6.12.2)
      System.IdentityModel.Tokens.Jwt (>= 6.12.2)
    Microsoft.IdentityModel.Tokens (6.12.2)
      Microsoft.CSharp (>= 4.5)
      Microsoft.IdentityModel.Logging (>= 6.12.2)
      System.Security.Cryptography.Cng (>= 4.5)
    Microsoft.IO.RecyclableMemoryStream (2.1.3)
    Microsoft.NET.Test.Sdk (17.3)
      Microsoft.CodeCoverage (>= 17.3)
      Microsoft.TestPlatform.TestHost (>= 17.3)
    Microsoft.NETCore.Platforms (5.0.3)
    Microsoft.TestPlatform.ObjectModel (17.3)
      NuGet.Frameworks (>= 5.11)
      System.Reflection.Metadata (>= 1.6)
    Microsoft.TestPlatform.TestHost (17.3)
      Microsoft.TestPlatform.ObjectModel (>= 17.3)
      Newtonsoft.Json (>= 9.0.1)
    Microsoft.Win32.Registry (5.0)
      System.Security.AccessControl (>= 5.0)
      System.Security.Principal.Windows (>= 5.0)
    Microsoft.Win32.SystemEvents (5.0)
      Microsoft.NETCore.Platforms (>= 5.0)
    Mono.Cecil (0.11.4)
    MySql.Data (8.0.30)
      Google.Protobuf (>= 3.19.4)
      K4os.Compression.LZ4.Streams (>= 1.2.6)
      Portable.BouncyCastle (>= 1.9)
      System.Buffers (>= 4.5.1)
      System.Configuration.ConfigurationManager (>= 4.4.1)
      System.Runtime.CompilerServices.Unsafe (>= 5.0)
      System.Security.Permissions (>= 4.7)
      System.Text.Encoding.CodePages (>= 4.4)
    MySqlConnector (2.1.13)
    Newtonsoft.Json (13.0.1)
    NuGet.Frameworks (6.3)
    Ply (0.3.1)
      FSharp.Core (>= 4.6.2)
      System.Threading.Tasks.Extensions (>= 4.5.4)
    Pomelo.EntityFrameworkCore.MySql (5.0.4)
      Microsoft.EntityFrameworkCore.Relational (>= 5.0.10 < 6.0)
      Microsoft.Extensions.DependencyInjection (>= 5.0.2)
      MySqlConnector (>= 1.3.13)
    Portable.BouncyCastle (1.9)
    Saturn (0.15)
      FSharp.Control.Websockets (>= 0.2.2)
      FSharp.Core (>= 5.0.1)
      Giraffe (>= 5.0)
      Microsoft.AspNetCore.Authentication.JwtBearer (>= 5.0.7)
    System.Buffers (4.5.1)
    System.Collections.Immutable (6.0)
      System.Memory (>= 4.5.4)
      System.Runtime.CompilerServices.Unsafe (>= 6.0)
    System.ComponentModel.Annotations (5.0)
    System.Configuration.ConfigurationManager (5.0)
      System.Security.Cryptography.ProtectedData (>= 5.0)
      System.Security.Permissions (>= 5.0)
    System.Diagnostics.DiagnosticSource (5.0.1)
    System.Drawing.Common (5.0.2)
      Microsoft.Win32.SystemEvents (>= 5.0)
    System.Formats.Asn1 (5.0)
    System.IdentityModel.Tokens.Jwt (6.12.2)
      Microsoft.IdentityModel.JsonWebTokens (>= 6.12.2)
      Microsoft.IdentityModel.Tokens (>= 6.12.2)
    System.Memory (4.5.4)
    System.Memory.Data (1.0.2)
      System.Text.Encodings.Web (>= 4.7.2)
      System.Text.Json (>= 4.6)
    System.Numerics.Vectors (4.5)
    System.Reactive (5.0)
    System.Reflection.Emit (4.7)
    System.Reflection.Emit.Lightweight (4.7)
    System.Reflection.Metadata (6.0.1)
      System.Collections.Immutable (>= 6.0)
    System.Runtime.CompilerServices.Unsafe (6.0)
    System.Security.AccessControl (5.0)
      Microsoft.NETCore.Platforms (>= 5.0)
      System.Security.Principal.Windows (>= 5.0)
    System.Security.Cryptography.Cng (5.0)
      System.Formats.Asn1 (>= 5.0)
    System.Security.Cryptography.Pkcs (5.0.1)
      System.Formats.Asn1 (>= 5.0)
      System.Security.Cryptography.Cng (>= 5.0)
    System.Security.Cryptography.ProtectedData (5.0)
    System.Security.Cryptography.Xml (5.0)
      System.Security.Cryptography.Pkcs (>= 5.0)
      System.Security.Permissions (>= 5.0)
    System.Security.Permissions (5.0)
      System.Security.AccessControl (>= 5.0)
      System.Windows.Extensions (>= 5.0)
    System.Security.Principal.Windows (5.0)
    System.Text.Encoding.CodePages (6.0)
      System.Runtime.CompilerServices.Unsafe (>= 6.0)
    System.Text.Encodings.Web (5.0.1)
    System.Text.Json (5.0.2)
    System.Threading.Tasks.Extensions (4.5.4)
    System.ValueTuple (4.5)
    System.Windows.Extensions (5.0)
      System.Drawing.Common (>= 5.0)
    Thoth.Json (6.0)
      Fable.Core (>= 3.1.6)
      FSharp.Core (>= 4.7.2)
    Utf8Json (1.3.7)
      System.Reflection.Emit (>= 4.3)
      System.Reflection.Emit.Lightweight (>= 4.3)
      System.Threading.Tasks.Extensions (>= 4.4)
      System.ValueTuple (>= 4.4)
    YoloDev.Expecto.TestSdk (0.13.3)
      Expecto (>= 9.0 < 10.0)
      FSharp.Core (>= 4.6.2)
      System.Collections.Immutable (>= 6.0)
```

**Comment by EspenBrun** [comment]
I have encountered this again when starting with the guide, so I have a minimal version where I encounter this bug. Closing this to reduce the clutter
