### ISSUE TITLE
Support EF Core 7

### ISSUE THREAD

**Issue by otto-gebb** [efcore/EFCore.FSharp#155]
Currently, if  the project uses EF Core 7, an error occurs on attempt to create a migration, similar to the one shown in a comment to #112:
> System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.Design.ICSharpHelper.Fragment ...

A workaround is to downgrade to EF Core 6.

**Comment by andre-dasilva** [comment]
Same for dotnet 8

**Comment by MaceWindu** [comment]
EF9 also broken as `ISqlExpressionFactory` has a lot of changes in v9:
```
System.MissingMethodException : Method not found: 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlUnaryExpression Microsoft.EntityFrameworkCore.Query.ISqlExpressionFactory.IsNull(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlExpression)'.
```

**Comment by blfuentes** [comment]
Not sure if this is exactly the problem I'm facing.
Using .net 8 and EF Core 6.0.7
```
<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Dapper" Version="2.1.35" />
		<PackageVersion Include="Dapper.FSharp" Version="4.9.0" />
		<PackageVersion Include="EntityFrameworkCore.FSharp" Version="6.0.7" />
		<PackageVersion Include="FSharp.Core" Version="8.0.401" />
		<PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
		<PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
		<PackageVersion Include="Microsoft.Data.Sqlite" Version="8.0.10" />
		<PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="8.0.10" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1" />
		<PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageVersion Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>
</Project>
```
And get this error when I try to add a migration:

> System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.Design.ICSharpHelper.Fragment(Microsoft.EntityFrameworkCore.Design.MethodCallCodeFragment, System.String, Boolean)'.
   at EntityFrameworkCore.FSharp.EFCoreFSharpServices.Microsoft.EntityFrameworkCore.Design.IDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureReferencedServices(IServiceCollection services, String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'System.String Microsoft.EntityFrameworkCore.Design.ICSharpHelper.Fragment(Microsoft.EntityFrameworkCore.Design.MethodCallCodeFragment, System.String, Boolean)'.
